module.exports = [
  'babel-polyfill',
  'react',
  'react-redux',
  'react-router',
  'react-dom',
  'redux',
  'redux-thunk',
  'seamless-immutable',
  'react-router-redux',
  'history',
  'lodash',
  'styled-components',
  'prop-types',
];
